### organism specific functions for the HiCdat
### automatically generated by HiCdat

f.get.chrom.sizes <- function() {
	out <- list(
		'3R' = 15000000
		)
	return(out)
}

f.get.frag.list <- function() {
	out <- list(
		'3R' = c(78259015, 93259016)
		)
	return(out)
}

f.get.relevant.chromosomes <- function() {
	out <- c('3R')
	return(out)
}

